# Generated by Django 4.1.1 on 2022-10-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('messsage', models.CharField(max_length=200, verbose_name='Mesaj')),
            ],
        ),
    ]
