# Generated by Django 4.1.1 on 2022-10-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmodel',
            old_name='messsage',
            new_name='message',
        ),
    ]
