# Generated by Django 4.1.1 on 2022-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_messsage_contactformmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='rating1',
            field=models.IntegerField(max_length=5, null=True, unique=True, verbose_name='rating1'),
        ),
        migrations.AddField(
            model_name='contactformmodel',
            name='rating2',
            field=models.IntegerField(max_length=5, null=True, unique=True, verbose_name='rating2'),
        ),
    ]
