# Generated by Django 4.1.1 on 2022-10-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_contactformmodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='message',
            field=models.CharField(max_length=200, null=True, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='rating2',
            field=models.IntegerField(default=0, null=True, verbose_name='rating2'),
        ),
    ]
