# Generated by Django 4.1.1 on 2022-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_alter_contactformmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='email',
            field=models.CharField(default='empty', max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='username',
            field=models.CharField(default='empty', max_length=50, verbose_name='Ad Soyad'),
        ),
    ]
