# Generated by Django 4.1.1 on 2022-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_alter_contactformmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='message',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Mesaj'),
        ),
    ]
