# Generated by Django 4.1.1 on 2022-10-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_alter_contactformmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='message',
            field=models.CharField(default=' ', max_length=200, null=True, verbose_name='Mesaj'),
        ),
    ]
