# Generated by Django 4.1.1 on 2022-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_alter_contactformmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Gönderilme Tarihi'),
        ),
    ]
