# Generated by Django 4.1.1 on 2022-11-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_contactformmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='email',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Email'),
        ),
    ]
